export const SCHOOL_FETCH_URL = '/api/schools'
export const STUDENT_FETCH_URL = '/api/students'
export const FETCH_SCHOOL_RESPONSE = 'FETCH_SCHOOL_RESPONSE'
export const FETCH_SCHOOL_REQUEST = 'FETCH_SCHOOL_REQUEST'
export const FETCH_SCHOOL_ERROR = 'FETCH_SCHOOL_ERROR'

export const FETCH_STUDENT_RESPONSE = 'FETCH_STUDENT_RESPONSE'
export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST'
export const FETCH_STUDENT_ERROR = 'FETCH_STUDENT_ERROR'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_RESPONSE = 'REGISTER_USER_RESPONSE'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const REGISTER_URL = '/api/register'